version: "3.2"
services:
  registry:
    image: registry:2
    ports:
      - 5000:5000
    environment:
      - REGISTRY_HTTP_SECRET=VERY_SECURE_PASS
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    container_name: registry
    volumes:
      - ./registry:/var/lib/registry
  ui:
    image: joxit/docker-registry-ui:static
    ports:
      - 8080:80
    environment:
      - REGISTRY_URL=http://registry:5000
    container_name: registry-ui